kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: azure-disk2
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modules-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-disk2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi