apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-db
  strategy: {}
  template:
    metadata:
      labels:
        app: vc-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: MSSQL_PID
          value: Express
        - name: SA_PASSWORD
          value: v!rto_Labs!
        image: mcr.microsoft.com/mssql/server:latest
        name: vc-db
        ports:
        - containerPort: 1433