apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\Utils\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vc-db
  name: vc-db
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: vc-db
status:
  loadBalancer: {}
