apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\Utils\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vc-platform-web
  name: vc-platform-web
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 80
  selector:
    io.kompose.service: vc-platform-web
status:
  loadBalancer: {}
