apiVersion: v1
kind: Service
metadata:
  name: vc-storefront-web
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: vc-dev-store
spec:
  ports:
  - port: 80
  selector:
    app: vc-storefront-web
  type: LoadBalancer
